### PR TITLE
Move magic strings to constants

### PR DESCRIPTION
**Pull request by elchininet**
This pull request moves multiple magic strings to a separate module to reuse them without the risk of making a typo.

### CODE REVIEW

**Comment by elchininet** [comment]
Hi @NemesisRE,
This one is just a refactoring of the code moving magic strings to constants.
Take a look when you have some time.
Regards.

**Comment by elchininet** [comment]
@NemesisRE,
I have a serie of refactorings like this one, I‘ll push the pull requests one by one because I am working them in different branches one dependant on the previous.

**Comment by NemesisRE** [comment]
alright do that, looks good so far. I am on vacation until 4.4.
if there is something urgent I will hopefully see it.

**Comment by elchininet** [comment]
@NemesisRE,
No urgent things, just these refactorings for now.
Enjoy your holidays!

**Pull request merged**
