### PR TITLE
Make a flow for automatic releases creation

### PR DESCRIPTION
**Pull request by elchininet**
This pull request creates a flow for automatic releases creation.

### CODE REVIEW

**Comment by elchininet** [comment]
@NemesisRE,
Let‘s test how it works. I have set it up to create the changelog from `1.7.8` instead from the last release to make it possible to generate releases notes and I have configure it to create just a draft. I‘ll test it on my side to see if it works properly and I‘ll delete the tag after that. I‘ll ley you know so you can test it out on your side too.

**Comment by elchininet** [comment]
Hi @NemesisRE,
It seems to work OK. [Check it out](https://github.com/NemesisRE/kiosk-mode/releases/tag/untagged-7dec845c7b169dd937cc).
Please, check it on your side. Make a patch release from the branch `npm version patch` and check if everything goes well for you.

**Comment by NemesisRE** [comment]
I like it, looks pretty good but what I am missing is the contributors. Somehow they (in our case you :)) were automatically added to the release, I think this should be in as an appreciation.

**Comment by elchininet** [comment]
> I like it, looks pretty good but what I am missing is the contributors. Somehow they (in our case you :)) were automatically added to the release, I think this should be in as an appreciation.

Hey, that should be easy to achieve.
Did you try to run it in your local?

**Comment by elchininet** [comment]
@NemesisRE,
I have added the contributor of each pull request.
https://github.com/NemesisRE/kiosk-mode/releases/tag/untagged-1edfe84f9b6e3f5e21fd

**Comment by elchininet** [comment]
@NemesisRE,
I have removed all testing parameters. Once this gets merged you can release from command line.

**Pull request merged**
